#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# custom startup
#export XCURSOR_THEME=Breeze
export PULSE_LATENCY_MSEC=30 mscore  #fix musesocre noise with pulseaudio
export QT_QPA_PLATFORMTHEME=gtk2  #qt6gtk2 and qt5-styleplugins required (aur)
# Hardware acceleration config
#export LIBVA_DRIVER_NAME=iHD #for intel-media-driver
#export VDPAU_DRIVER=va_gl
#export LIBVA_DRIVER_NAME=radeonsi #for AMDGPU driver
export LIBVA_DRIVER_NAME=nvidia #nvidia-utils required
export VDPAU_DRIVER=nvidia
#export MOZ_X11_EGL=1 #if firefox is before 94
export MOZ_WEBRENDER=1
# graphical authentication agent
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# gcin input
#export GTK_IM_MODULE=gcin
#export QT_IM_MODULE=gcin
#export XMODIFIERS="@im=gcin"
#gcin &

# ibus input
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"
ibus-daemon -drxR &

# wallpaper
nitrogen --restore &
DISPLAY=":0" picom -b &
#imwheel -b 45 -g &
exec qtile start
