# Don't print a new line at the start of the prompt
add_newline = false
#command_timeout = 800

# The line_break module separates the prompt into two lines.
[line_break]
disabled = true

#[character]                             # The name of the module we are configuring is "character" 
#success_symbol = "[➜](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
#error_symbol = "[✗](bold red) "

[status]                               # The "status" module displays the exit code of the previous command.
disabled = false
format = '[$status]($style) '

#[username]
#show_always = true

#[hostname]
#ssh_only = false
